// <auto-generated />
namespace QuanLyGaraOto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QLGarav411 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QLGarav411));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291605498_QLGarav411"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
