// <auto-generated />
namespace QuanLyGaraOto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QLGaraV61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QLGaraV61));
        
        string IMigrationMetadata.Id
        {
            get { return "201805150627599_QLGaraV61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
